extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  document-end: disable
  
ignore: |
  .github/
  .nx/
  node_modules/
  .venv/
  venv/
  vendor/
  packages/coreboot/
  packages/qemu/
  tmp/
  .cache/
  build/
  dist/
  *.min.yml
  *.min.yaml